USE [master]
GO

CREATE LOGIN [readonlyadmin] WITH 
	PASSWORD=N'ROadminpass1234!', 
	DEFAULT_DATABASE=[master], 
	DEFAULT_LANGUAGE=[us_english], 
	CHECK_EXPIRATION=OFF, 
	CHECK_POLICY=OFF
GO

ALTER SERVER ROLE [Readonly] ADD MEMBER [readonlyadmin]
GO