sp_change_users_login 'AUTO_FIX', 'Test'

USE master 
GO
CREATE LOGIN TestUser  WITH PASSWORD = 'readOaad1213nlyuser123!';
GO
CREATE SERVER ROLE TestRole 
GO
GRANT VIEW ANY DEFINITION TO TestRole
Go
GRANT VIEW SERVER STATE TO TestRole
GO
GRANT CONTROL SERVER TO TestRole;
GO
ALTER SERVER ROLE TestRole ADD MEMBER TestUser
GO
DENY ALTER ANY SERVER ROLE TO TestRole;
GO
DENY ALTER ANY LOGIN TO TestRole;
GO
DENY ALTER ANY DATABASE TO TestRole;
GO
DENY ALTER SETTINGS TO TestRole;
GO
DENY ALTER ANY SERVER AUDIT TO TestRole;
GO
DENY CREATE SERVER ROLE TO TestRole; 
GO
DENY UNSAFE ASSEMBLY TO TestRole;

use [TSK_f79f72cc-52e2-4cc4-ab2f-18da61411025]
GO

CREATE USER [Test] FOR LOGIN [TestUser]
GO

GRANT SELECT TO [Test]
GO
DENY DELETE TO [Test]
GO
DENY INSERT TO [Test]
GO
DENY UPDATE TO [Test]
GO